spring:
    config:
        activate:
            on-profile: prod
    datasource:
        username: admin
        password: admin
        url: jdbc:mysql://localhost:3600/ventedb
    jpa:
        show-sql: 'true'
        hibernate:
            ddl-auto: create
            dialect:
    servlet:
        multipart:
            enabled: 'true'
            max-file-size: 140MB
twilio:
    account_sid: AC42eb71ec7d3ed278469d88a6380132f8
    auth_token: 6e8807d1a72316a69c007f819a95e5cf
    trial_number: +17164543577
jwt:
    secret: 'jpgfop8WyHu1ULufJJXm0PV20/J9BD2HqTAKDZ+/qTv4glDJjyIlo/PIhehQJqSrdIim4fjuwkax9FOCuFQ9nesv32hZ6rbFjETeQSxUPjNzsYGOuULWSR3cI8FuV9InlSZQ7q6dEunLPRf/rZujxiAxGzY8zrMehjM5LNdl7qDEOsc109Yy3HBbOwUdJyyTg/GRPwklLogw9kkldz5+wMvwOT38IlkO2rCrqJpqqt1KmxdOQNbeGwNzZiGiuYId'
