server:
    port: 8081
    error:
        include-message: always
        include-binding-errors: always

spring:
    profiles:
        active: development
---

spring:
    profiles: development
    datasource:
        username: marco
        password: 1234
        url: jdbc:postgresql://localhost:5432/ventedb
#       schema: classpath:/data.sql
    jpa:
        show-sql: 'true'
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: 'true'
            max-file-size: 50MB
twilio:
    account_sid: AC42eb71ec7d3ed278469d88a6380132f8
    auth_token: 6e8807d1a72316a69c007f819a95e5cf
    trial_number: +17164543577
jwt:
    secret: 'jpgfop8WyHu1ULufJJXm0PV20/J9BD2HqTAKDZ+/qTv4glDJjyIlo/PIhehQJqSrdIim4fjuwkax9FOCuFQ9nesv32hZ6rbFjETeQSxUPjNzsYGOuULWSR3cI8FuV9InlSZQ7q6dEunLPRf/rZujxiAxGzY8zrMehjM5LNdl7qDEOsc109Yy3HBbOwUdJyyTg/GRPwklLogw9kkldz5+wMvwOT38IlkO2rCrqJpqqt1KmxdOQNbeGwNzZiGiuYId'

---

spring:
    profiles: production
    datasource:
        url: https://tictac-dev.com/ventedb
        username: admin
        password: admin1234
    jpa:
        show-sql: 'true'
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            enabled: 'true'
            max-file-size: 100MB
twilio:
    account_sid: ''
    auth_token: ''
    trial_number: ''
jwt:
    secret: ''
